before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -y libssl-dev libpcre3-dev wget unzip libopencore-amrwb0 libopencore-amrnb0 libfaac0 libass4 libgsm1 libmp3lame0 libopenjpeg2 libschroedinger-1.0-0 libspeex1 libtheora0  libva1  libvpx1 libxvidcore4
    - sudo wget http://installrepo.kaltura.org/releases/kaltura-ffmpeg2.1.3_amd64.deb 
    - sudo wget http://installrepo.kaltura.org/releases/kaltura-ffmpeg-deb-deps/libx264-123_0.123.2189+git35cf912-1_amd64.deb
    - sudo dpkg -i libx264-123_0.123.2189+git35cf912-1_amd64.deb
    - sudo wget http://installrepo.kaltura.org/releases/kaltura-ffmpeg-deb-deps/libfdk-aac0_0.1.3-1_amd64.deb
    - sudo dpkg -i libfdk-aac0_0.1.3-1_amd64.deb
    - sudo dpkg -i kaltura-ffmpeg2.1.3_amd64.deb
language: c
compiler:
    - clang
    - gcc
script: ./travis_build.sh
notifications:
  email:
    recipients:
      - eran.kornblau@kaltura.com
      - jess.portnoy@kaltura.com
    on_success: change
    on_failure: always
